[ML]
# How much data will be used for train, val and test. If -1, then all available data is used.
# 2^15 = 32768, 2^16 = 65536, 2^17 = 131072, 2^18 = 262144, 2 ^ 19 = 524288
DatasetSize: 262144
# Train, Val and Test are ratios which should sum to 1.0
Train: 0.625
Test: 0.25
Val: 0.125
Epochs: 1
Hidden: 10 10
Dropout: 0.0
Activation: relu
Optimizer: Adam
BatchSize: 64
LR: 1e-3
# Class tolerance for logging Train and Val accuracy. Test accuracy is logged for all possible class tolerances.
AccuracyEps: 0
# Standard deviation of additive white Gaussian noise added to dataset to simulate different SNR. Used only by run_traces_noisy.py
StdDev: 1.0


[OPTUNA]
# Number of trials for optimization
Trials: 2
# Epochs is fixed and is not optimized
Epochs: 30
# Train and val split ratio should sum to 1, Test has its own dataset
Train: 0.7
Val: 0.3
# Batchsize is fixed and is not optimized
BatchSize: 64
# Upper and lower bound separated by space
NumLayers: 2 5
# Upper and lower bound of layer size
LayerSize: 64 512
# Optimizer is fixed
Optimizer: adam
# Activation is fixed
Activation: relu
# LR is fixed
LR: 1e-5
# Integer between 0 and 33
AccuracyEps: 0
