[MILP]
#This section corresponds to the script "MILP+SMT/Trivium_MILP_PredictedHW_Correction_CHES-submission.py". The parameters are defined as follows:
#state_size represents the size of the internal state of the target cipher.
#N_round represents the number of rounds for which Hamming weight information is available. Denoted by # Rounds in the manuscript.
#trials represents the number of independent experiments.
#tolerance, t reprsents that HW_noisy[i] - t <= HW[i] <= HW_noisy[i] + t for all i,
#where HW is the array of original Hamming weights and HW_noisy is the array of noisy Hamming weights.
#mc_len represents the width of the microcontroller
#diff represents the number of incoming bits to each block starting from B0 (see section 4.3.2 of the manuscript).
#Currently the array diff is adjusted as per Trivium cipher and 32-bit microcontroller.
#distribution represents the accuracy of ML output with respect to varying tolerance in the format (accuracy of tolerance 0, accuracy of tolerance 1, ....)
#The input parameters below are assigned as per the first row of Table 4.

state_size = 288
N_round = 110
trials = 1000
tolerance = 3
mc_len = 32
diff = [1, 1, 2, 1, 1, 2, 1, 1, 1]
distribution =  [0.39266, 0.86615, 0.98234, 0.99784, 0.99965, 0.99992, 0.99999, 1.0]



[SMT-HW]
#This section corresponds to the script "MILP+SMT/Trivium_SMT-HW-code-CHES-submission.py". The input parameters are adjusted as per the first row of Table 5(a).
state_size = 288             
mc_len = 8                  
tolerance = 1
N_round = 110  
#N_round is denoted by #Rounds in tables of the manuscript.
init = 0
#init represents the phase; 0 for pseudo-random phase and 1 for initialisation phase.                   
G_pos = []
#G_pos represents the state bits that has to be guessed (any number between 0-state_size-1) 
trials = 20                   
z_act = 0
#z_act represents the usage of keystream bits while forming equations, 0 for no and 1 for yes.
multi_thread = 1
#Use Multi-threading, multi_thread = 1 for Yes; multi_thread = 0 for No
n_thread = 3
#n_thread is the number of thread to be used if multi_thread = 1 else it won't be considered             



[SMT-HD]
#This section corresponds to the script "MILP+SMT/Trivium_SMT-HD-code-CHES-submission.py". The input parameters are adjusted as per the 8th row of Table 7.
state_size = 288
N_round = 150
G_pos = [60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79]  
#G_pos refers to the column named Guessed Bits in Table 6 of the manuscript.
init = 1
z_act = 0
tolerance = 1
trials = 5 
multi_thread = 0
#Use Multi-threading, multi_thread = 1 for Yes; multi_thread = 0 for No
n_thread = 3
#n_thread is the number of thread to be used if multi_thread = 1 else it won't be considered 
